"""Add extraction pipeline tables

Revision ID: fff59326eca4
Revises: 
Create Date: 2026-03-04 14:26:20.877473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff59326eca4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('ocr_method', sa.String(length=30), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('total_line_items', sa.Integer(), nullable=True),
    sa.Column('escalation_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_jobs_celery_task_id'), 'extraction_jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_extraction_jobs_id'), 'extraction_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_extraction_jobs_job_id'), 'extraction_jobs', ['job_id'], unique=True)
    op.create_index('ix_extraction_jobs_status_created', 'extraction_jobs', ['status', 'created_at'], unique=False)
    op.create_table('file_watcher_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_file_watcher_state_id'), 'file_watcher_state', ['id'], unique=False)
    op.create_table('task_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_results_id'), 'task_results', ['id'], unique=False)
    op.create_index(op.f('ix_task_results_task_id'), 'task_results', ['task_id'], unique=True)
    op.create_table('extracted_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('manufacturer_part_number', sa.String(length=100), nullable=True),
    sa.Column('original_uom', sa.String(length=20), nullable=True),
    sa.Column('detected_pack_quantity', sa.Integer(), nullable=True),
    sa.Column('canonical_base_uom', sa.String(length=10), nullable=True),
    sa.Column('price_per_base_unit', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('escalation_flag', sa.Boolean(), nullable=True),
    sa.Column('escalation_reasons', sa.JSON(), nullable=True),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('sac_code', sa.String(length=20), nullable=True),
    sa.Column('raw_line', sa.Text(), nullable=True),
    sa.Column('pack_info', sa.JSON(), nullable=True),
    sa.Column('lookup_source', sa.String(length=30), nullable=True),
    sa.Column('lookup_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['extraction_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_line_items_id'), 'extracted_line_items', ['id'], unique=False)
    op.create_index(op.f('ix_extracted_line_items_job_id'), 'extracted_line_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_extracted_line_items_manufacturer_part_number'), 'extracted_line_items', ['manufacturer_part_number'], unique=False)
    op.create_index('ix_line_items_escalation', 'extracted_line_items', ['escalation_flag'], unique=False)
    op.create_index('ix_line_items_job_confidence', 'extracted_line_items', ['job_id', 'confidence_score'], unique=False)
    op.create_table('lookup_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_item_id', sa.Integer(), nullable=False),
    sa.Column('lookup_source', sa.String(length=30), nullable=False),
    sa.Column('lookup_query', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('resolved_uom', sa.String(length=20), nullable=True),
    sa.Column('resolved_pack_quantity', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['line_item_id'], ['extracted_line_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_audit_logs_id'), 'lookup_audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lookup_audit_logs_id'), table_name='lookup_audit_logs')
    op.drop_table('lookup_audit_logs')
    op.drop_index('ix_line_items_job_confidence', table_name='extracted_line_items')
    op.drop_index('ix_line_items_escalation', table_name='extracted_line_items')
    op.drop_index(op.f('ix_extracted_line_items_manufacturer_part_number'), table_name='extracted_line_items')
    op.drop_index(op.f('ix_extracted_line_items_job_id'), table_name='extracted_line_items')
    op.drop_index(op.f('ix_extracted_line_items_id'), table_name='extracted_line_items')
    op.drop_table('extracted_line_items')
    op.drop_index(op.f('ix_task_results_task_id'), table_name='task_results')
    op.drop_index(op.f('ix_task_results_id'), table_name='task_results')
    op.drop_table('task_results')
    op.drop_index(op.f('ix_file_watcher_state_id'), table_name='file_watcher_state')
    op.drop_table('file_watcher_state')
    op.drop_index('ix_extraction_jobs_status_created', table_name='extraction_jobs')
    op.drop_index(op.f('ix_extraction_jobs_job_id'), table_name='extraction_jobs')
    op.drop_index(op.f('ix_extraction_jobs_id'), table_name='extraction_jobs')
    op.drop_index(op.f('ix_extraction_jobs_celery_task_id'), table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    # ### end Alembic commands ###
